/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as LauncherRouteImport } from './routes/launcher'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ModesRouteImport } from './routes/modes'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SupportRouteImport } from './routes/support'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'
import { Route as CheckoutOrderIdRouteImport } from './routes/checkout.$orderId'
import { Route as SupportIdRouteImport } from './routes/support_.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const LauncherRoute = LauncherRouteImport.update({
  id: '/launcher',
  path: '/launcher',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ModesRoute = ModesRouteImport.update({
  id: '/modes',
  path: '/modes',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutOrderIdRoute = CheckoutOrderIdRouteImport.update({
  id: '/checkout/$orderId',
  path: '/checkout/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIdRoute = SupportIdRouteImport.update({
  id: '/support_/$id',
  path: '/support/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/launcher': typeof LauncherRoute
  '/login': typeof LoginRoute
  '/modes': typeof ModesRoute
  '/panel': typeof PanelRoute
  '/rules': typeof RulesRoute
  '/shop': typeof ShopRoute
  '/support': typeof SupportRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/support/$id': typeof SupportIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/launcher': typeof LauncherRoute
  '/login': typeof LoginRoute
  '/modes': typeof ModesRoute
  '/panel': typeof PanelRoute
  '/rules': typeof RulesRoute
  '/shop': typeof ShopRoute
  '/support': typeof SupportRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/support/$id': typeof SupportIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/launcher': typeof LauncherRoute
  '/login': typeof LoginRoute
  '/modes': typeof ModesRoute
  '/panel': typeof PanelRoute
  '/rules': typeof RulesRoute
  '/shop': typeof ShopRoute
  '/support': typeof SupportRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/support_/$id': typeof SupportIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/launcher'
    | '/login'
    | '/modes'
    | '/panel'
    | '/rules'
    | '/shop'
    | '/support'
    | '/blog/$slug'
    | '/checkout/$orderId'
    | '/support/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/launcher'
    | '/login'
    | '/modes'
    | '/panel'
    | '/rules'
    | '/shop'
    | '/support'
    | '/blog/$slug'
    | '/checkout/$orderId'
    | '/support/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/launcher'
    | '/login'
    | '/modes'
    | '/panel'
    | '/rules'
    | '/shop'
    | '/support'
    | '/blog_/$slug'
    | '/checkout/$orderId'
    | '/support_/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  LauncherRoute: typeof LauncherRoute
  LoginRoute: typeof LoginRoute
  ModesRoute: typeof ModesRoute
  PanelRoute: typeof PanelRoute
  RulesRoute: typeof RulesRoute
  ShopRoute: typeof ShopRoute
  SupportRoute: typeof SupportRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CheckoutOrderIdRoute: typeof CheckoutOrderIdRoute
  SupportIdRoute: typeof SupportIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launcher': {
      id: '/launcher'
      path: '/launcher'
      fullPath: '/launcher'
      preLoaderRoute: typeof LauncherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modes': {
      id: '/modes'
      path: '/modes'
      fullPath: '/modes'
      preLoaderRoute: typeof ModesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$orderId': {
      id: '/checkout/$orderId'
      path: '/checkout/$orderId'
      fullPath: '/checkout/$orderId'
      preLoaderRoute: typeof CheckoutOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support_/$id': {
      id: '/support_/$id'
      path: '/support/$id'
      fullPath: '/support/$id'
      preLoaderRoute: typeof SupportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  LauncherRoute: LauncherRoute,
  LoginRoute: LoginRoute,
  ModesRoute: ModesRoute,
  PanelRoute: PanelRoute,
  RulesRoute: RulesRoute,
  ShopRoute: ShopRoute,
  SupportRoute: SupportRoute,
  BlogSlugRoute: BlogSlugRoute,
  CheckoutOrderIdRoute: CheckoutOrderIdRoute,
  SupportIdRoute: SupportIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
